# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-26 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0027_auto_20190225_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='loc_Pic',
            new_name='pic',
        ),
        migrations.RenameField(
            model_name='userhotelreservation',
            old_name='hotel_Name',
            new_name='hotel',
        ),
        migrations.RenameField(
            model_name='userhotelreservation',
            old_name='user_Name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='loc_Name',
        ),
    ]
