INSERT INTO places_country(name) VALUES ('United States');
INSERT INTO places_country(name) VALUES ('Samoa');
INSERT INTO places_country(name) VALUES ('Niue');
INSERT INTO places_country(name) VALUES ('Cook Islands');
INSERT INTO places_country(name) VALUES ('French Polynesia');
INSERT INTO places_country(name) VALUES ('Canada');
INSERT INTO places_country(name) VALUES ('Mexico');
INSERT INTO places_country(name) VALUES ('Chile');
INSERT INTO places_country(name) VALUES ('Guatemala');
INSERT INTO places_country(name) VALUES ('El Salvador');
INSERT INTO places_country(name) VALUES ('Belize');
INSERT INTO places_country(name) VALUES ('Honduras');
INSERT INTO places_country(name) VALUES ('Nicaragua');
INSERT INTO places_country(name) VALUES ('Costa Rica');
INSERT INTO places_country(name) VALUES ('Cuba');
INSERT INTO places_country(name) VALUES ('Malaysia');
INSERT INTO places_country(name) VALUES ('Ecuador');
INSERT INTO places_country(name) VALUES ('Panama');
INSERT INTO places_country(name) VALUES ('The Bahamas');
INSERT INTO places_country(name) VALUES ('Peru');
INSERT INTO places_country(name) VALUES ('Jamaica');
INSERT INTO places_country(name) VALUES ('Colombia');
INSERT INTO places_country(name) VALUES ('Venezuela');
INSERT INTO places_country(name) VALUES ('Turks and Caicos Islands');
INSERT INTO places_country(name) VALUES ('Aruba');
INSERT INTO places_country(name) VALUES ('Dominican Republic');
INSERT INTO places_country(name) VALUES ('Brazil');
INSERT INTO places_country(name) VALUES ('Netherlands Antilles');
INSERT INTO places_country(name) VALUES ('Argentina');
INSERT INTO places_country(name) VALUES ('Bolivia');
INSERT INTO places_country(name) VALUES ('Puerto Rico');
INSERT INTO places_country(name) VALUES ('Grenada');
INSERT INTO places_country(name) VALUES ('Bermuda');
INSERT INTO places_country(name) VALUES ('British Virgin Islands');
INSERT INTO places_country(name) VALUES ('Anguilla');
INSERT INTO places_country(name) VALUES ('Guadeloupe');
INSERT INTO places_country(name) VALUES ('Trinidad and Tobago');
INSERT INTO places_country(name) VALUES ('Dominica');
INSERT INTO places_country(name) VALUES ('Saint Vincent and the Grenadines');
INSERT INTO places_country(name) VALUES ('St. Lucia');
INSERT INTO places_country(name) VALUES ('Barbados');
INSERT INTO places_country(name) VALUES ('Hong Kong');
INSERT INTO places_country(name) VALUES ('Paraguay');
INSERT INTO places_country(name) VALUES ('Réunion');
INSERT INTO places_country(name) VALUES ('Uruguay');
INSERT INTO places_country(name) VALUES ('Suriname');
INSERT INTO places_country(name) VALUES ('French Guiana');
INSERT INTO places_country(name) VALUES ('Greenland');
INSERT INTO places_country(name) VALUES ('Italy');
INSERT INTO places_country(name) VALUES ('Portugal');
INSERT INTO places_country(name) VALUES ('Iceland');
INSERT INTO places_country(name) VALUES ('Senegal');
INSERT INTO places_country(name) VALUES ('The Gambia');
INSERT INTO places_country(name) VALUES ('Mauritania');
INSERT INTO places_country(name) VALUES ('Guinea-Bissau');
INSERT INTO places_country(name) VALUES ('Guinea');
INSERT INTO places_country(name) VALUES ('Sierra Leone');
INSERT INTO places_country(name) VALUES ('Western Sahara');
INSERT INTO places_country(name) VALUES ('Liberia');
INSERT INTO places_country(name) VALUES ('Mali');
INSERT INTO places_country(name) VALUES ('Morocco');
INSERT INTO places_country(name) VALUES ('Faroe Islands');
INSERT INTO places_country(name) VALUES ('Ireland');
INSERT INTO places_country(name) VALUES ('Spain');
INSERT INTO places_country(name) VALUES ('United Kingdom');
INSERT INTO places_country(name) VALUES ('Gibraltar');
INSERT INTO places_country(name) VALUES ('Côte d''Ivoire');
INSERT INTO places_country(name) VALUES ('Australia');
INSERT INTO places_country(name) VALUES ('France');
INSERT INTO places_country(name) VALUES ('Burkina Faso');
INSERT INTO places_country(name) VALUES ('Ghana');
INSERT INTO places_country(name) VALUES ('Togo');
INSERT INTO places_country(name) VALUES ('Niger');
INSERT INTO places_country(name) VALUES ('Benin');
INSERT INTO places_country(name) VALUES ('Algeria');
INSERT INTO places_country(name) VALUES ('Nigeria');
INSERT INTO places_country(name) VALUES ('Netherlands');
INSERT INTO places_country(name) VALUES ('Belgium');
INSERT INTO places_country(name) VALUES ('Norway');
INSERT INTO places_country(name) VALUES ('Switzerland');
INSERT INTO places_country(name) VALUES ('Germany');
INSERT INTO places_country(name) VALUES ('Monaco');
INSERT INTO places_country(name) VALUES ('Philippines');
INSERT INTO places_country(name) VALUES ('Gabon');
INSERT INTO places_country(name) VALUES ('Liechtenstein');
INSERT INTO places_country(name) VALUES ('Cameroon');
INSERT INTO places_country(name) VALUES ('Tunisia');
INSERT INTO places_country(name) VALUES ('Denmark');
INSERT INTO places_country(name) VALUES ('Austria');
INSERT INTO places_country(name) VALUES ('Sweden');
INSERT INTO places_country(name) VALUES ('Libya');
INSERT INTO places_country(name) VALUES ('Angola');
INSERT INTO places_country(name) VALUES ('Czech Republic');
INSERT INTO places_country(name) VALUES ('Malta');
INSERT INTO places_country(name) VALUES ('Slovenia');
INSERT INTO places_country(name) VALUES ('Chad');
INSERT INTO places_country(name) VALUES ('Republic of the Congo');
INSERT INTO places_country(name) VALUES ('Democratic Republic of the Congo');
INSERT INTO places_country(name) VALUES ('Svalbard and Jan Mayen');
INSERT INTO places_country(name) VALUES ('Croatia');
INSERT INTO places_country(name) VALUES ('Slovakia');
INSERT INTO places_country(name) VALUES ('Bosnia and Herzegovina');
INSERT INTO places_country(name) VALUES ('South Africa');
INSERT INTO places_country(name) VALUES ('Central African Republic');
INSERT INTO places_country(name) VALUES ('Hungary');
INSERT INTO places_country(name) VALUES ('Montenegro');
INSERT INTO places_country(name) VALUES ('Albania');
INSERT INTO places_country(name) VALUES ('Poland');
INSERT INTO places_country(name) VALUES ('Serbia');
INSERT INTO places_country(name) VALUES ('Russia');
INSERT INTO places_country(name) VALUES ('Kosovo');
INSERT INTO places_country(name) VALUES ('Macedonia');
INSERT INTO places_country(name) VALUES ('Bulgaria');
INSERT INTO places_country(name) VALUES ('Greece');
INSERT INTO places_country(name) VALUES ('Finland');
INSERT INTO places_country(name) VALUES ('Ukraine');
INSERT INTO places_country(name) VALUES ('Latvia');
INSERT INTO places_country(name) VALUES ('Estonia');
INSERT INTO places_country(name) VALUES ('Lithuania');
INSERT INTO places_country(name) VALUES ('Zambia');
INSERT INTO places_country(name) VALUES ('Botswana');
INSERT INTO places_country(name) VALUES ('Romania');
INSERT INTO places_country(name) VALUES ('Syria');
INSERT INTO places_country(name) VALUES ('Lesotho');
INSERT INTO places_country(name) VALUES ('Belarus');
INSERT INTO places_country(name) VALUES ('Zimbabwe');
INSERT INTO places_country(name) VALUES ('Turkey');
INSERT INTO places_country(name) VALUES ('Burundi');
INSERT INTO places_country(name) VALUES ('Moldova');
INSERT INTO places_country(name) VALUES ('Egypt');
INSERT INTO places_country(name) VALUES ('Rwanda');
INSERT INTO places_country(name) VALUES ('Swaziland');
INSERT INTO places_country(name) VALUES ('Sudan');
INSERT INTO places_country(name) VALUES ('Mozambique');
INSERT INTO places_country(name) VALUES ('Tanzania');
INSERT INTO places_country(name) VALUES ('Cyprus');
INSERT INTO places_country(name) VALUES ('Malawi');
INSERT INTO places_country(name) VALUES ('Palestine');
INSERT INTO places_country(name) VALUES ('Israel');
INSERT INTO places_country(name) VALUES ('Lebanon');
INSERT INTO places_country(name) VALUES ('Jordan');
INSERT INTO places_country(name) VALUES ('Kenya');
INSERT INTO places_country(name) VALUES ('Ethiopia');
INSERT INTO places_country(name) VALUES ('Eritrea');
INSERT INTO places_country(name) VALUES ('Saudi Arabia');
INSERT INTO places_country(name) VALUES ('Georgia');
INSERT INTO places_country(name) VALUES ('Comoros');
INSERT INTO places_country(name) VALUES ('Iraq');
INSERT INTO places_country(name) VALUES ('Somalia');
INSERT INTO places_country(name) VALUES ('Armenia');
INSERT INTO places_country(name) VALUES ('Mayotte');
INSERT INTO places_country(name) VALUES ('Iran');
INSERT INTO places_country(name) VALUES ('Azerbaijan');
INSERT INTO places_country(name) VALUES ('Madagascar');
INSERT INTO places_country(name) VALUES ('Bahrain');
INSERT INTO places_country(name) VALUES ('Qatar');
INSERT INTO places_country(name) VALUES ('United Arab Emirates');
INSERT INTO places_country(name) VALUES ('Mauritius');
INSERT INTO places_country(name) VALUES ('Turkmenistan');
INSERT INTO places_country(name) VALUES ('Oman');
INSERT INTO places_country(name) VALUES ('Uzbekistan');
INSERT INTO places_country(name) VALUES ('Afghanistan');
INSERT INTO places_country(name) VALUES ('Pakistan');
INSERT INTO places_country(name) VALUES ('India');
INSERT INTO places_country(name) VALUES ('Tajikistan');
INSERT INTO places_country(name) VALUES ('Kazakhstan');
INSERT INTO places_country(name) VALUES ('Kyrgyzstan');
INSERT INTO places_country(name) VALUES ('Sri Lanka');
INSERT INTO places_country(name) VALUES ('Nepal');
INSERT INTO places_country(name) VALUES ('China');
INSERT INTO places_country(name) VALUES ('Bhutan');
INSERT INTO places_country(name) VALUES ('Bangladesh');
INSERT INTO places_country(name) VALUES ('Indonesia');
INSERT INTO places_country(name) VALUES ('Myanmar');
INSERT INTO places_country(name) VALUES ('Thailand');
INSERT INTO places_country(name) VALUES ('Laos');
INSERT INTO places_country(name) VALUES ('Singapore');
INSERT INTO places_country(name) VALUES ('Cambodia');
INSERT INTO places_country(name) VALUES ('Vietnam');
INSERT INTO places_country(name) VALUES ('Mongolia');
INSERT INTO places_country(name) VALUES ('Macau');
INSERT INTO places_country(name) VALUES ('Brunei');
INSERT INTO places_country(name) VALUES ('Taiwan');
INSERT INTO places_country(name) VALUES ('North Korea');
INSERT INTO places_country(name) VALUES ('South Korea');
INSERT INTO places_country(name) VALUES ('Japan');
INSERT INTO places_country(name) VALUES ('Palau');
INSERT INTO places_country(name) VALUES ('Papua New Guinea');
INSERT INTO places_country(name) VALUES ('Federated States of Micronesia');
INSERT INTO places_country(name) VALUES ('Solomon Islands');
INSERT INTO places_country(name) VALUES ('New Caledonia');
INSERT INTO places_country(name) VALUES ('New Zealand');
INSERT INTO places_country(name) VALUES ('Marshall Islands');
INSERT INTO places_country(name) VALUES ('Fiji');
INSERT INTO places_country(name) VALUES ('Tuvalu');
INSERT INTO places_country(name) VALUES ('Tonga');
INSERT INTO places_country(name) VALUES ('Haiti');
INSERT INTO places_country(name) VALUES ('Martinique');
INSERT INTO places_country(name) VALUES ('Andorra');
INSERT INTO places_country(name) VALUES ('Luxembourg');
INSERT INTO places_country(name) VALUES ('San Marino');
INSERT INTO places_country(name) VALUES ('Djibouti');
INSERT INTO places_country(name) VALUES ('Yemen');
INSERT INTO places_country(name) VALUES ('Kuwait');
INSERT INTO places_country(name) VALUES ('Republic of Maldives');
INSERT INTO places_country(name) VALUES ('Republic of Palau');
INSERT INTO places_country(name) VALUES ('Nauru');
INSERT INTO places_country(name) VALUES ('Vanuatu');
INSERT INTO places_country(name) VALUES ('Wallis and Futuna');