# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-26 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_Id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_Updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_Name',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='city_Name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_Created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_Text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_Updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_Name',
            new_name='user',
        ),
    ]
